import { Language, AiTone, AiVoiceGender, ReportType } from './types';

export const APP_TITLE = "PersonaCheck AI";
export const GEMINI_TEXT_MODEL = "gemini-2.5-flash-preview-04-17"; // Updated model

export const TARGET_QUESTIONS_PER_ASSESSMENT = 12; // Target number of MCQs
export const ALL_QUESTIONS_ASKED_MARKER = "PersonaCraft::ALL_QUESTIONS_ASKED"; // Note: This marker is internal, keeping as is unless direct user visibility is an issue.

export const LOCALES: Record<Language, Record<string, string>> = {
  [Language.English]: {
    welcomeTitle: "Welcome to PersonaCheck AI!",
    namePrompt: "Hi there! What’s your name?",
    namePlaceholder: "Enter your name",
    submitName: "Let's Begin",
    configTitle: "Personalize Your AI Assistant",
    languageSelect: "Choose your language:",
    toneSelect: "Select AI tone:",
    voiceGenderSelect: "Select AI voice gender:",
    reportTypeSelect: "Choose report type:",
    startChat: "Start My Assessment", 
    send: "Send",
    generatingReport: "Generating your personalized report...",
    reportTitle: "Your Personalized Personality Report",
    reportTypeGenerated: "Report Type: {reportType}",
    downloadSummaryPdf: "Download Summary (PDF)",
    exportFullScriptDocx: "Export Full Script (DOCX)",
    exportKeyNotesTxt: "Export Key Notes (TXT)",
    thankYouMessage: "Thank you, {userName}, for completing your assessment! Here’s your personalized report.",
    footerText: "Developed with ❤️ by Saqib Sarwar",
    nextQuestionError: "Sorry, I couldn't come up with the next question. Please try again.",
    reportGenerationError: "Oops! Something went wrong while generating your report. Please try again later.",
    reportSection_summary: "Summary",
    reportSection_mbti: "MBTI Personality Type",
    reportSection_iqEstimate: "IQ Estimate",
    reportSection_intelligenceType: "Type of Intelligence",
    reportSection_introvertExtrovertAmbivert: "Introvert/Extrovert/Ambivert",
    reportSection_creativityLevel: "Creativity Level",
    reportSection_learningStyle: "Learning Style",
    reportSection_emotionalIntelligence: "Emotional Intelligence (EQ)",
    reportSection_socialBehavior: "Social Behavior",
    reportSection_confidenceLevel: "Confidence Level",
    reportSection_stressManagement: "Stress Management",
    reportSection_communicationStyle: "Communication Style",
    reportSection_patienceConsistency: "Patience & Consistency",
    reportSection_decisionMakingPattern: "Decision-Making Pattern",
    reportSection_habitAnalysis: "Habit Analysis",
    reportSection_leadershipQuality: "Leadership Quality",
    reportSection_memoryAttentionSpan: "Memory & Attention Span",
    reportSection_optimismPessimismScale: "Optimism vs. Pessimism",
    reportSection_riskTakingBehavior: "Risk-Taking Behavior",
    reportSection_suggestedCareerPaths: "Suggested Career Paths",
    reportSection_personalGrowthAdvice: "Personal Growth Advice",
    reportSection_motivationSource: "Primary Motivation Source",
    reportSection_strengths: "Predicted Strengths",
    reportSection_weaknesses: "Predicted Weaknesses",
    reportSection_suggestionsForImprovement: "Suggestions for Improvement",
    reportSection_funInsights: "Fun Insights",
    reportSection_motivationalQuote: "Motivational Quote",
    reportSection_skillsToDevelopForCareer: "Skills to Develop for Career",
    reportSection_empathyLevel: "Empathy Level",
    loading: "Loading...",
    error: "Error",
    tryAgain: "Try Again",
    defaultReportValue: "Analysis pending...",
    exportError: "Failed to export file.",
    exportOptionsTitle: "Export Your Insights",
    reportType_QuickSummary: "Quick Summary",
    reportType_DetailedMBTI: "Detailed MBTI Focus",
    reportType_CareerFocus: "Career Focus",
    reportType_EmotionalIntelligenceFocus: "Emotional Intelligence (EQ) Focus",
    reportType_FullAnalysis: "Full Analysis",
    assessmentStartMessage: "Starting assessment for {reportType}. My name is {userName}. Language: {language}, Tone: {tone}.",
    selectedOptionText: "You selected: ",
    generateReportPrompt: "You've completed all questions! Generate your report now?", 
    generateReportButton: "Generate My Personality Report Now",
    allQuestionsAnswered: "All questions answered. Proceed to generate your report.",
    continueButton: "Continue",
  },
  [Language.Hindi]: {
    welcomeTitle: "पर्सोनाचेक एआई में आपका स्वागत है!",
    namePrompt: "नमस्ते! आपका नाम क्या है?",
    namePlaceholder: "अपना नाम दर्ज करें",
    submitName: "चलिए शुरू करते हैं",
    configTitle: "अपने एआई सहायक को वैयक्तिकृत करें",
    languageSelect: "अपनी भाषा चुनें:",
    toneSelect: "एआई टोन चुनें:",
    voiceGenderSelect: "एआई आवाज लिंग चुनें:",
    reportTypeSelect: "रिपोर्ट का प्रकार चुनें:",
    startChat: "मेरा मूल्यांकन शुरू करें",
    send: "भेजें",
    generatingReport: "आपकी व्यक्तिगत रिपोर्ट तैयार की जा रही है...",
    reportTitle: "आपकी व्यक्तिगत व्यक्तित्व रिपोर्ट",
    reportTypeGenerated: "रिपोर्ट प्रकार: {reportType}",
    thankYouMessage: "धन्यवाद, {userName}, अपना मूल्यांकन पूरा करने के लिए! यहाँ आपकी व्यक्तिगत रिपोर्ट है।",
    footerText: "❤️ साकिब सरवर द्वारा विकसित",
    nextQuestionError: "क्षमा करें, मैं अगला प्रश्न नहीं सोच सका। कृपया पुनः प्रयास करें।",
    reportGenerationError: "उफ़! आपकी रिपोर्ट बनाते समय कुछ गड़बड़ हो गई। कृपया बाद में पुनः प्रयास करें।",
    reportType_QuickSummary: "त्वरित सारांश",
    reportType_DetailedMBTI: "विस्तृत MBTI फोकस",
    reportType_CareerFocus: "कैरियर फोकस",
    reportType_EmotionalIntelligenceFocus: "भावनात्मक बुद्धिमत्ता (EQ) फोकस",
    reportType_FullAnalysis: "पूर्ण विश्लेषण",
    assessmentStartMessage: "{reportType} के लिए मूल्यांकन शुरू हो रहा है। मेरा नाम {userName} है। भाषा: {language}, टोन: {tone}।",
    selectedOptionText: "आपने चुना: ",
    generateReportPrompt: "आपने सभी प्रश्न पूरे कर लिए हैं! अब अपनी रिपोर्ट तैयार करें?",
    generateReportButton: "मेरी व्यक्तित्व रिपोर्ट अभी तैयार करें",
    allQuestionsAnswered: "सभी प्रश्नों के उत्तर दे दिए गए हैं। अपनी रिपोर्ट तैयार करने के लिए आगे बढ़ें।",
    continueButton: "जारी रखें",
  },
  [Language.Urdu]: {
    welcomeTitle: "پرسوناچیک اے آئی میں خوش آمدید!",
    namePrompt: "سلام! آپ کا نام کیا ہے؟",
    reportTypeSelect: "رپورٹ کی قسم منتخب کریں:",
    startChat: "میرا جائزہ شروع کریں",
    reportType_QuickSummary: "فوری خلاصہ",
    reportType_DetailedMBTI: "تفصیلی MBTI فوکس",
    reportType_CareerFocus: "کیریئر فوکس",
    reportType_EmotionalIntelligenceFocus: "جذباتی ذہانت (EQ) فوکس",
    reportType_FullAnalysis: "مکمل تجزیہ",
    assessmentStartMessage: "{reportType} کے لئے جائزہ شروع ہو رہا ہے۔ میرا نام {userName} ہے۔ زبان: {language}، لہجہ: {tone}۔",
    selectedOptionText: "آپ نے منتخب کیا: ",
    generateReportPrompt: "آپ نے تمام سوالات مکمل کر لیے ہیں! اب اپنی رپورٹ بنائیں؟",
    generateReportButton: "میری شخصیت کی رپورٹ ابھی بنائیں",
    allQuestionsAnswered: "تمام سوالات کے جوابات دے دیے گئے ہیں۔ اپنی رپورٹ بنانے کے لیے آگے بڑھیں۔",
    continueButton: "جاری رکھیں",
  },
  [Language.Kashmiri]: {
    welcomeTitle: "پرسوناچیک اے آیس منز استقبال!",
    namePrompt: "آدا ب! ژھۄ کیا ناو چھُ؟",
    reportTypeSelect: "رِپورٹُک قسٕم ژارِو:",
    startChat: "میون جایزٕ شروع کٔرِو",
    reportType_QuickSummary: "فوری خلاصہ",
    reportType_DetailedMBTI: "تفصیلی MBTI فوکس",
    reportType_CareerFocus: "کیریئر فوکس",
    reportType_EmotionalIntelligenceFocus: "جذباتی ذہانت (EQ) فوکس",
    reportType_FullAnalysis: "مکمل تجزیہ",
    assessmentStartMessage: "{reportType} خٲطرٕ جایزٕ چھُ شروع گژھان۔ مٮ۪ون ناو چھُ {userName}۔ زبان: {language}، انداز: {tone}۔",
    selectedOptionText: "ژھٔ چُھ منتخب کۆرمُت: ",
    generateReportPrompt: "ژھٔ وۆتِھؠ سٲری سوال مُکمل کٔرِتھ! وَنؠ بَنٲیِو پنٕنؠ رِپورٹ؟",
    generateReportButton: "میٲن شخصیتٕچ رِپورٹ وَنؠ تیار کٔرِو",
    allQuestionsAnswered: "سٲروَے سوالَن ہُنٛد جواب چھُ دِنہٕ آمُت۔ پنٕنؠ رِپورٹ تیار کرنہٕ خٲطرٕ برٛۆہ کن گژھِو۔",
    continueButton: "جاری تھاوِو",
  },
  [Language.Hinglish]: {
    welcomeTitle: "Welcome to PersonaCheck AI!",
    namePrompt: "Hi there! Aapka naam kya hai?",
    reportTypeSelect: "Report type chuno:",
    startChat: "Mera assessment shuru karo",
    reportType_QuickSummary: "Quick Summary",
    reportType_DetailedMBTI: "Detailed MBTI Focus",
    reportType_CareerFocus: "Career Focus",
    reportType_EmotionalIntelligenceFocus: "Emotional Intelligence (EQ) Focus",
    reportType_FullAnalysis: "Full Analysis",
    assessmentStartMessage: "{reportType} ke liye assessment shuru ho raha hai. Mera naam {userName} hai. Language: {language}, Tone: {tone}.",
    selectedOptionText: "Aapne select kiya: ",
    generateReportPrompt: "Aapne saare questions complete kar liye hain! Ab apni report generate karein?",
    generateReportButton: "Meri personality report abhi generate karo",
    allQuestionsAnswered: "Sabhi questions ke answers de diye gaye hain. Apni report generate karne ke liye aage badhein.",
    continueButton: "Continue",
  },
};

export const AVAILABLE_LANGUAGES = [
  { value: Language.English, label: "English" },
  { value: Language.Hindi, label: "हिंदी (Hindi)" },
  { value: Language.Urdu, label: "اردو (Urdu)" },
  { value: Language.Kashmiri, label: "کٲشُر (Kashmiri)" },
  { value: Language.Hinglish, label: "Hinglish" },
];

export const AVAILABLE_TONES = [
  { value: AiTone.Cheerful, label: "Cheerful" },
  { value: AiTone.Calm, label: "Calm" },
  { value: AiTone.Serious, label: "Serious" },
  { value: AiTone.Motivational, label: "Motivational" },
];

export const AVAILABLE_VOICE_GENDERS = [
  { value: AiVoiceGender.Male, label: "Male" },
  { value: AiVoiceGender.Female, label: "Female" },
];

export const AVAILABLE_REPORT_TYPES = (translate: (key: string) => string) => [
  { value: ReportType.FullAnalysis, label: translate('reportType_FullAnalysis') },
  { value: ReportType.QuickSummary, label: translate('reportType_QuickSummary') },
  { value: ReportType.DetailedMBTI, label: translate('reportType_DetailedMBTI') },
  { value: ReportType.CareerFocus, label: translate('reportType_CareerFocus') },
  { value: ReportType.EmotionalIntelligenceFocus, label: translate('reportType_EmotionalIntelligenceFocus') },
];